### PR TITLE
Add httpHost, httpHostSsl and chain handlebar helpers in order to port custom httpd ports in conga-aem-definitions

### PR DESCRIPTION
**Pull request by tobias-richter**
This PR adds the handlers
* httpHost
* httpHostSsl
* chain

This is required by https://github.com/wcm-io-devops/conga-aem-definitions/pull/32 in order to render custom Ports for http and https

### CODE REVIEW

**Comment by stefanseifert** [comment]
concerning the "chain" helper - do we really need it?
following the discussion here: https://github.com/wycats/handlebars.js/issues/304#issuecomment-129703835 it is possible to chain helpers in handlebars with a special syntax like `{{pluralize (titleize (humanize schema.name))}}`.
disclaimer: this post is from handlebars.js, not sure if this also works for handlebars.java

if we still need such a "chain" helper, it should not be part of the conga-aem-plugin, but of conga itself because it's completely generic and in no way AEM or dispatcher-specific.

**Comment by stefanseifert** [comment]
and it would be good to use the new features somewhere in the sample of this project, so they are not only used in the synthetic unit test.

**Comment by tobias-richter** [comment]
I seems that my search was not good enough. Thanks for pointing me to the native syntax.
I already changed it in https://github.com/wcm-io-devops/conga-aem-definitions/pull/32/commits/3423f849fea69166102cd654bb697b8a4b9e30e0

I removed the ChainHelper and added the new helpers in the project sample.

**Comment by stefanseifert** [comment]
thanks - i've applied it with some cosmetic changes.

**Pull request merged**
